deploy:
  image: insideworld.asuscomm.com/images/maven:latest
  script:
    - export
    - 'mvn deploy'
  only:
    - master

cleanup:
  image: insideworld.asuscomm.com/images/docker/dind:latest
  script:
    - rm -r -f /gitlab/m2/insideworld
  dependencies:
    - deploy